# This action is responsible for running a spellcheck against `main` each time we make changes.
name: Spellcheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check spelling
      uses: check-spelling/check-spelling@0.0.16-alpha
